### ISSUE TITLE
dockerized version

### ISSUE THREAD

**Issue by x0rzkov** [goavega-software/mustard#1]
Hi guys,

Hope you are all well !

I was wondering if you could provide a dockerized version of mustard with a docker-compose. 

That would awesome.

Thanks in advance for any insights or inputs on that topic.

Cheers,
X

**Comment by sn123** [comment]
Sure can, any reason you’re looking for docker compose? I think a Dockerfile should suffice since it doesn’t really have multi container setup unless you’re looking at running Vue UI in a separate container.

**Comment by x0rzkov** [comment]
I was thinking about a compose as you have a kafka layer ? does it not imply to have zookeeper also ?

**Comment by sn123** [comment]
Got it. Since Mustard is primarily a Kafka Listener, I wasn't sure what you'd need the Docker compose for but now if I get it right - you're looking for a compose which has Kafka brokers, Zookeeper and Mustard as containers. Fairly doable but might be a while before I can get to it - since right now the top most priority is to add NRT graph widgets using ApexChart and Kafka listeners.
